[package]
name = "krakenapi"
version = "0.1.0"
authors = ["Caleb Crane <calebccrane@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 =      "0.13.0"
http =        "0.2.2"
hyper =       "0.13.9"
hyper-tls =   "0.4.3"
indexmap =    "1.6.1"
rust-crypto = "0.2.36"
serde =       { version = "1.0", features = ["derive"] }
serde_json =  "1.0.60"

[dev-dependencies]
tokio = { version = "0.2.2", features = ["full"] }
